services:
    upload_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: upload_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - postgres

    postgres:
        image: postgres
        container_name: upl_postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network
        expose:
            - 5432
        ports:
            - "12345:5432"

    upload_pgadmin:
        image: dpage/pgadmin4
        container_name: upload_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "8000:80"
        networks:
            - app-network

    upload_web:
        container_name: upload_web
        image: nginx:alpine  # Use the Nginx image
        ports:
            - "8001:80"  # Map port 9000 on the host to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - upload_app  # Ensure PHP-FPM is started before Nginx
        networks:
            - app-network  # Connect to the custom network

volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
